# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# Demo 3-8-21 15:52
version: 2.1

executors:

  my_docker_executor:
    docker:
      - image: circleci/node:7.10
      
  my_linux_machine:
    machine: true
    
  my_macos_machine:
    macos:
      xcode: "9.0"

jobs:

  cow-install:
    executor: my_docker_executor

    steps:
      - run: sudo apt-get install cowsay
      - run: sudo cowsay "You installed cowsay. Yay."

  build:
    executor: my_docker_executor

    working_directory: ~/repo

    steps:
      - run:
          command: |
            cowsay "Now building React app"

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  job1-wf1:
    executor: my_docker_executor
    steps:
      - run: echo "This is a job in in workflow 1"
   
  job2-wf1:
    executor: my_docker_executor
    steps:
      - run: echo "This is a second job in in workflow 1"
      
  job1-wf2:
    executor: my_docker_executor
    steps:
      - run: echo "This is a job in in workflow 2"

workflows:
  version: 2
  workflow1:
    jobs:
      - job1-wf1
      - job2-wf1:
          requires:
            - job1-wf1

  workflow2:
    jobs:
      - job1-wf2
